#include "src/main.c"
#include "src/freecam.c"
#include "src/play.c"

#include "../taascene/src/scene.c"
#include "../taascene/src/sceneanim.c"
#include "../taascene/src/scenefile.c"
#include "../taascene/src/scenematerial.c"
#include "../taascene/src/scenemesh.c"
#include "../taascene/src/scenenode.c"
#include "../taascene/src/sceneskel.c"
#include "../taascene/src/scenetexture.c"

#include "../taasdk/src/filestream.c"
#include "../taasdk/src/keyboard.c"
#include "../taasdk/src/log.c"
#include "../taasdk/src/mouse.c"
#include "../taasdk/src/gl.c"
#include "../taasdk/src/glcontext.c"
#include "../taasdk/src/system.c"
#include "../taasdk/src/timer.c"
#include "../taasdk/src/window.c"
